# Note: The "from" keys in this file refers to the physical keys, which
# generally means that it is based on QWERTY layout even if you are using
# Dvorak.

- intercept: KEY_CAPSLOCK
  ontap: KEY_ESC
  onhold: KEY_LEFTCTRL

- intercept: KEY_ENTER
  # not necessary: ontap: KEY_ENTER is inferred if left empty
  onhold: KEY_RIGHTCTRL

# this is a layer. hold space (onhold) contains several remappings
- intercept: KEY_TAB
  onhold:

  # special chars
  # - from: KEY_E
  #   to: KEY_ESC

  # alternative syntax
  - {from: KEY_D, to: KEY_DELETE}
  - {from: KEY_B, to: KEY_BACKSPACE}

  # arrow keys
  - {from: KEY_I, to: KEY_UP}
  - {from: KEY_K, to: KEY_DOWN}
  - {from: KEY_J, to: KEY_LEFT}
  - {from: KEY_L, to: KEY_RIGHT}

  # page up/down keys
  - {from: KEY_E, to: KEY_PAGEUP}
  - {from: KEY_D, to: KEY_PAGEDOWN}
  - {from: KEY_S, to: KEY_HOME}
  - {from: KEY_F, to: KEY_END}

  # number row, to F keys
  - {from: KEY_1, to: KEY_F1}
  - {from: KEY_2, to: KEY_F2}
  - {from: KEY_3, to: KEY_F3}
  - {from: KEY_4, to: KEY_F4}
  - {from: KEY_5, to: KEY_F5}
  - {from: KEY_6, to: KEY_F6}
  - {from: KEY_7, to: KEY_F7}
  - {from: KEY_8, to: KEY_F8}
  - {from: KEY_9, to: KEY_F9}
  - {from: KEY_0, to: KEY_F10}
  - {from: KEY_MINUS, to: KEY_F11}
  - {from: KEY_EQUAL, to: KEY_F12}

  # xf86 audio
  - {from: KEY_M,     to: KEY_MUTE}
  - {from: KEY_COMMA, to: KEY_VOLUMEDOWN}
  - {from: KEY_DOT,   to: KEY_VOLUMEUP}

  # brightness
  - {from: KEY_X, to: KEY_BRIGHTNESSDOWN}
  - {from: KEY_C, to: KEY_BRIGHTNESSUP}

  # mouse navigation
  - {from: BTN_LEFT,  to: BTN_BACK}
  - {from: BTN_RIGHT, to: BTN_FORWARD}
